Rama flor2
FlorBelmonte/TrabajoVeterinarias pull request #4
Opened 2022-10-31 00:03 UTC by FlorBelmonte

2022-11-01 12:33 UTC, gonzalezvictorjuan requested changes
Falta el gitignore, estan subiendo la carpeta node_modules y en total serian 129 archivos, esto no tiene que suceder

2022-11-01 12:55 UTC, FlorBelmonte commented
> Falta el gitignore, estan subiendo la carpeta node_modules y en total serian 129 archivos, esto no tiene que suceder

como agrego el gitignore?

2022-11-09 12:53 UTC, gonzalezvictorjuan approved these changes

2022-11-14 22:29 UTC, gonzalezvictorjuan approved these changes

2022-11-14 22:29 UTC, gonzalezvictorjuan commented
tienen estos conflicotos, estaria bueno que los puedan resolver antes de avanzar, me avisan si necesitan ayuda

2022-11-15 21:43 UTC, merged